### ISSUE TITLE
hỗ trợ đa ngôn ngữ cho app

### ISSUE THREAD

**Issue by Rolbackse** [Rolbackse/Kanayomi#12]

**Comment by Rolbackse** [comment]
Version tới sẽ hỗ trợ các ngôn ngữ sau:
Anh (eng)
Việt (vie)
Trung  (zho)
Hàn (kor)

Mã ngôn ngữ tham khảo ở đây
https://en.wikipedia.org/wiki/ISO_639

**Comment by Rolbackse** [comment]
Thiết kế mới của dialog dịch. @haha3170 tham khảo nhé
https://drive.google.com/open?id=110lTe5EgRepBC3DmHCGge0i-obs9SJrSg7uYC3ZLzUc

**Comment by Rolbackse** [comment]
Từ điển Nhật Việt của glosbe không có nhiều tiếng việt. Hơn nữa ko có phần hán tự. Vì thế với những người sử dụng tiếng việt thì sẽ sử dụng API của mazii. Cụ thể theo API dưới:

API tra từ:
http://mazii.net/api/search/(Từ cần tra được encode bởi URL Encode)/PageZise/Page
Ví dụ: http://mazii.net/api/search/%E6%97%A5%E6%9C%AC%E8%AA%9E/30/1

API Hán Tự:
http://mazii.net/api/mazii/(Chữ hán muốn tra)/Số lượng từ tối đa muốn tra
Ví dụ: http://mazii.net/api/mazii/%E6%97%A5%E6%9C%AC%E8%AA%9E/10

API Ví dụ:
http://mazii.net/api/smile/(Từ muốn tra)
Ví dụ: http://mazii.net/api/smile/%E6%97%A5%E6%9C%AC%E8%AA%9E

**Comment by haha3170** [comment]
mở từ detail info về chữ Hán trong popup bằng cách click vào chữ Hán đó à ?

**Comment by Rolbackse** [comment]
không, thêm 1 tab chữ hán giống như tab nghĩa và tab ví dụ

**Comment by Rolbackse** [comment]
Hàm để lấy link audio của mazii

```java
  /***
     * convert link audio từ từ vựng
     * @param phrase từ vựng
     * @return link audio của phrase
     */
public static String convertPhraseToMp3(String phrase) {
        if (TextUtils.isEmpty(phrase))
            return null;
        phrase = phrase.replaceAll("「", "");
        phrase = phrase.replaceAll("」", "");
        StringBuilder builder = new StringBuilder("http://data.mazii.net/audios/");
        for (int n = 0; n < phrase.length(); n++) {
            String hex = String.format("%04x", (int) phrase.charAt(n)).toUpperCase();
            builder.append(hex);
            if (n < phrase.length() - 1) {
                builder.append("_");
            }
        }
        builder.append(".mp3");
        return builder.toString();
    }
```

**Comment by haha3170** [comment]
ok

**Comment by haha3170** [comment]
public static String convertPhraseToMp3(String phrase) {

phrase lấy ở đâu nhỉ ?

**Comment by haha3170** [comment]
Bên glosbe ko có chữ Hán nhưng mình lấy Tab chữ Hán của mazi cũng đc.
Ngoài phần dịch nghiã Kanji, bộ ra thì Người nước ngoài có thể tham khảo đc.

**Comment by Rolbackse** [comment]
ok cai nay se tien hanh lam luon

**Comment by haha3170** [comment]
done
