### ISSUE TITLE
Move nightMode button từ navigation -> floating button (UI/UX)

### ISSUE THREAD

**Issue by haha3170** [Rolbackse/Kanayomi#20]

**Comment by Rolbackse** [comment]
Hiện tại phía Android đang thiết kế như thế này. Nếu cho thêm night mode nữa thì chưa rõ sẽ như thế nào.
![screenshot_20180423-100826](https://user-images.githubusercontent.com/2811638/39102411-90dfacec-46de-11e8-9784-f66382aeb381.png)

**Comment by haha3170** [comment]
1, Sao ko bỏ FuriType đi ?
2, Bên iOS đang cho attach file.
![img_20180423_154248](https://user-images.githubusercontent.com/1861174/39110775-54698ba0-470d-11e8-93b4-2bb80038af94.jpg)

**Comment by toannv53** [comment]
attach file nghĩa là sao nhỉ?
Không cho nó đổi kiểu furigana ah

**Comment by haha3170** [comment]
à, tham khảo bên iOS bằng ảnh đính kèm.
Chức năng đổi kiểu Furigana ko mấy ai dùng đâu.

**Comment by Rolbackse** [comment]
android da thiet ke lai. ben ios tham khao nhe
