### ISSUE TITLE
Update lại PR app đầy đủ nội dung app & chuẩn SEO trong Google Play

### ISSUE THREAD

**Issue by haha3170** [Rolbackse/Kanayomi#23]

**Comment by haha3170** [comment]
A few tips for a perfect description:

Use the maximum possible number of characters for description. 3000-3500 char is OK.
Localize description to ALL possible languages.
Look for mid and long-tail keywords and add them to your description.
Use bullet points to organize the information in a clear and visual way for the user.
Describe the best features of your app.
Write in short paragraphs without an overload of information.
Include emoji 😉 ✔ or format text with HTML.
If your app has won a contest or award, brag about it!
Include a call-to-action that contains a sense of urgency (e.g. “Download now and start an adventure”)
Support your description with your social media profiles or links to communities of users of your app.
And check these requirements from Google what NOT to do 🙂
https://www.apptamin.com/blog/optimize-play-store-app/

**Comment by Rolbackse** [comment]
hầu hết là có đủ rồi
