### ISSUE TITLE
NHK có video mà has_image, audio, video đều false

### ISSUE THREAD

**Issue by haha3170** [Rolbackse/Kanayomi#24]
id=5185738681352192
--
`{"result":{"code":0,"message":"Success"},"data":{"items":{"5185738681352192":{"id":5185738681352192,"categoryId":1,"title":"衆参予算委 きょう集中審議 与野党の対立続く見通し","url":"http://www3.nhk.or.jp/news/html/20180426/k10011417661000.html","totalPage":0,"total":3,"facebook":0,"tweet":0,"hatena":0,"gplus":0,"hasVideo":false,"hasImage":false,"hasAudio":false,"needToLogin":false,"favorite":false,"publishDate":1524683597000,"titleKana":[{"text":"衆参","base_form":"衆参","hiragana":"しゅうさん","katakana":"シュウサン","romaji":"shuusan","has_furi":true,"is_break":false,"style":1,"type":1,"is_meaning":true},{"text":"予算","base_form":"予算","hiragana":"よさん","katakana":"ヨサ`

**Comment by Rolbackse** [comment]
server chua thuc hien crawl video cho bao nhk nen ko co.
