### ISSUE TITLE
Thêm indicator vào trong bài báo bài báo chi tiết

### ISSUE THREAD

**Issue by Rolbackse** [Rolbackse/Kanayomi#25]
bên trong bài báo cần cho thêm indicator vào trong để cho người dùng biết là có thể  swipe qua lại giữa các bài báo.

**Comment by Rolbackse** [comment]
done

**Comment by Rolbackse** [comment]
man hinh phia android
![device-2018-05-13-123320](https://user-images.githubusercontent.com/2811638/39963568-e8bded7c-56a9-11e8-98ad-136149ac7039.png)

**Comment by Rolbackse** [comment]
tinh hinh ios the nao roi

**Comment by haha3170** [comment]
Bên iOS chưa có chức năng swipe để hiện Detail các bài viết.
Để t thêm chức năng này đã.

**Comment by haha3170** [comment]
done
