### ISSUE TITLE
Tìm một vài  Theme wordpress phù hợp với KanaYomi 

### ISSUE THREAD

**Issue by haha3170** [Rolbackse/Kanayomi#47]

**Comment by quanph24** [comment]
3 theme theo kinh nghiệm lựa chọn của Tuân.
https://postimg.cc/image/5yc24ubmv/
https://postimg.cc/image/9j7xnt8dz/
https://postimg.cc/image/8tp5bhpuv/

**Comment by haha3170** [comment]
t vote cái thứ 2 nhất nhé, tiếp sau là cái thứ 3.
@Rolbackse @robotbatbai r nghĩ sao ?

**Comment by haduytuan** [comment]
@haha3170 @quanph24 @Rolbackse backse @robotbatbai
Theme GrandNews Full Crack : 
https://postimg.cc/image/9j7xnt8dz/
[grandmagazine-v1.9.installable.zip](https://github.com/Rolbackse/Kanayomi/files/2132024/grandmagazine-v1.9.installable.zip)

Theme FlatNews Full Crack : 
https://postimg.cc/image/8tp5bhpuv/
[Flatnews.zip](https://github.com/Rolbackse/Kanayomi/files/2132040/Flatnews.zip)

**Comment by Rolbackse** [comment]
dùng theme grandnews đi

**Comment by haduytuan** [comment]
OK
Chốt GrandNews nhé mọi người 
@haha3170 @quanph24 @Rolbackse @robotbatbai @binhvh
