### ISSUE TITLE
Note meeting 180624

### ISSUE THREAD

**Issue by haha3170** [Rolbackse/Kanayomi#52]
<h1>Đề xuất cải thiện & phương hướng sắp tới cho KanaYomi: </h1>
<h2>I, App </h2>
1, Đổi category, thêm Hot Page, clone đánh giá hot total view các báo.

2, Cải thiện UI thân thiên người dùng, image to, dễ nhìn ,...

3, Nghiên cứu Key words.

4, Tạo video quảng cáo sản phẩm.

5, Sửa bug sớm nhất.

6, Hạn chế quảng cáo, lôi kéo người dùng.

7, Đặt default ngôn ngữ máy & bỏ chọn ngôn ngữ trong Từ điển.

<h2>II, Fanpange </h2>
1, Đổi title app "Học tiếng nhật cùng ..."

2, Thay banner.

3, Đăng 1 or 2 bài trên ngày với link bài đăng dạng iOS, android or blog.

<h2>III, Web </h2>
1, Chốt ngôn ngữ  PHP - framework Laravel

2, Quân code cùng Thuê Outsource.

3, Thế Anh PM dự án web, Toàn support design + server.

<h2> IV, Blog </h2>
1, Chốt wordpress.

2, Tuân tổng hợp new theme gửi Group.

3, Tuân nghiên cứu thêm chút về Seo App trên Google Play, App Store.
<h3> V, Sale </h2>
1, Thế Anh tổng hợp & đánh giá các chiến lược sale.

**Comment by robotbatbai** [comment]
Theo bảng bàng này thống nhất vai trò của ae trong team : 
1. Chiến : PM, Android, facebook FB
2. Toàn : desinger, IOS, API 
3. Tuấn : Blog, Seo Blog, 
4. Thế Anh : Seo App, Web, cải tiến UI APP, Sale 
5. Quân : support tạo Blog, code Web 

=> ok chưa @haha3170  nhỉ

**Comment by haha3170** [comment]
@robotbatbai m cải tiến UI APP là sao nhỉ ?

**Comment by robotbatbai** [comment]
@haha3170 
đề xuất thui, để giao diện thân thiện vs người dùng hơn thui :))
