### ISSUE TITLE
Xin đánh giá về bố cục blog tại đại chỉ IP : 35.202.18.42  !!!

### ISSUE THREAD

**Issue by haduytuan** [Rolbackse/Kanayomi#58]
Mọi người truy cập vào địa chỉ http://35.202.18.42/ để khám phá và đánh giá xem cấu trúc,logo đã được chưa.Nếu OK thì đống ý sang tuần làm nội dung nhé...!!!

**Comment by haha3170** [comment]
@haduytuan bố cục thế ok r nhé.
Logo ở issue khác.
