### ISSUE TITLE
Help (có bàn tay chỉ)

### ISSUE THREAD

**Issue by haha3170** [Rolbackse/Kanayomi#8]

**Comment by Rolbackse** [comment]
ios xong chua nhi

**Comment by haha3170** [comment]
Bàn tay chỉ thì ok nhưng bên iOS chưa có tính năng mở detail như Android.
Cần p thêm chức năng này.

**Comment by haha3170** [comment]
Cho xem lại cái icon swipe gesture trên Android với.

**Comment by haha3170** [comment]
done
